config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  root to: "posts#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }, skip: [:registrations]
  devise_scope :user do
    get 'users/sign_up', to: 'users/registrations#new', as: :new_user_registration
    post 'users', to: 'users/registrations#create', as: :user_registration
    get 'users/edit', to: 'users/registrations#edit', as: :edit_user_registration
    put 'users', to: 'users/registrations#update'
    patch 'users', to: 'users/registrations#update'
    delete 'users', to: 'users/registrations#destroy'
  end
  resources :posts do
    post 'create_txt', on: :collection
    resources :tags
    resources :comments
  end
  delete "posts", to: "posts#destroy", as: :delete_post
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :post
  has_many :notifications, dependent: :destroy
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :post
  belongs_to :comment
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  validates :title, presence: true
  validates :user_id, presence: true
  paginates_per 3
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :tags, dependent: :destroy
  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    %w[title content]
  end


  def self.ransackable_associations(auth_object = nil)
    %w[user tags]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post

  def self.ransackable_attributes(auth_object = nil)
    %w[tag_name]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_query
  before_action :set_locale

  def set_query
    @query = Post.ransack(params[:q])
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[new create]
  before_action :authenticate_user!, except: %i[ new create ]

  def new
  end

  def create
    @comment = Comment.new(comment_params)
    if current_user != nil
      @comment.user_id = current_user.id
    else
      @comment.user_id = nil
    end
    @comment.post = @post
    if @comment.save
      comment_id = @comment.id
      @notifications = Notification.create(user_id: @post.user_id, post_id: @post.id, comment_id: comment_id)
      redirect_to post_path(@post), notice: t('flash.notice.comment_create')
    else
      redirect_to post_comments_path(@post), status: :unprocessable_entity
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/posts_controller.rb
require 'sidekiq'
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[ new create update destroy]
  before_action :verify_user, only: [:show]
  include Sidekiq::Job

  def index
    @posts = Post.order(updated_at: :desc).page(params[:page])
  end

  def show
    if @delete_notification
      Notification.where(post_id: @post.id, user_id: current_user.id).destroy_all
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post), notice: t('flash.notice.post_create')
    else
      redirect_to posts_path, status: :unprocessable_entity
    end
  end

  def create_txt
    if params[:txt_files].nil?
      redirect_to posts_path, status: :unprocessable_entity
    else
      params[:txt_files].each do |file|
        file_content = file.read
        lines = file_content.split("\n")
        title = lines.first.strip
        content = lines[1..].join("\n").strip
        UploadJob.perform_async(title, content, current_user.id)
      end
      @times = params[:txt_files].size
      if @times == 1
        redirect_to posts_path, notice: (t('Completed_job'))
      else
        redirect_to posts_path, notice: (t('Completed_jobs', times: @times))
      end
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: t('flash.notice.post_update')
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: t('flash.notice.post_destroy')
  end

  private

  def set_post
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def verify_user
    if current_user && current_user.id == Post.find(params[:id]).user_id
      @delete_notification = true
    else
      @delete_notification = false
    end
  end

  def post_params
    params.require(:post).permit(:content, :title)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @query = Post.ransack(params[:q])
    @posts = @query.result.page(params[:page])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_post, only: %i[new]
  before_action :authenticate_user!, except: %i[ new create ]

  def new
    @tag = Tag.new
  end


  def create
    if params[:tag][:tag_name].blank?
      redirect_to post_path(params[:post_id]), status: :unprocessable_entity
    else
      completed_jobs = 0
      tag_names = params[:tag][:tag_name].split(' ')
      job_count = tag_names.size
      tag_names.each do |tag_name|
        post_id = params[:post_id]
        completed_jobs += 1
        UploadtagJob.perform_async(tag_name, post_id)
      end
      @times = tag_names.size
      if @times == 1
        redirect_to post_path(params[:post_id]), notice: t('flash.notice.tag_create') if completed_jobs == job_count
      else
        redirect_to post_path(params[:post_id]), notice: t('flash.notice.tags_create', times: @times) if completed_jobs == job_count
      end
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def tag_params
    params.require(:tag).permit(:tag_name)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div class="container px-4 mb-4 mt-5 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Comment form -->
      <div class="post-preview">
        <h2 class="text-center mb-5"><%=t'Add_a_comment'%></h2>
        <%= simple_form_for [@post, Comment.new] do |f| %>
          <%= f.input :content, label: (t'Write_your_comment_here') %>
          <div class="d-grid gap-2">
            <%= f.button :submit, (t'Create_comment'), class: "btn btn-primary" %>
            <%= link_to (t'Cancel'), post_path(@post), class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maino App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-dark-subtle">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post form -->
      <div class="post-preview">
        <h2 class="text-center"><%=t'Edit_your_post'%></h2>
        <%= simple_form_for @post do |f| %>
          <%= f.input :title, label: (t'Edit_your_title_here') %>
          <%= f.input :content, label: (t'Edit_your_content_here') %>
          <div class="d-grid gap-2">
            <%= f.button :submit, (t'Edit_post'), class: "btn btn-primary" %>
            <%= link_to (t'Cancel'), post_path(@post), class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div>
  <div class="flex mb-4 mt-5 div_post ">
    <% if current_user != nil%>
      <%= link_to t('New_post'), new_post_path, class:"popup_post row gx-4 fs-3 gx-lg-5 justify-content-center"%>
    <% end %>
  </div>
  <div>
    <%@posts.each do |post| %>
      <div class=" container px-4 my-3 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7 shadowposts">
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="<%= post_path(post)%>">
                        <h2 class="post-title"><%= post.title %></h2>
                        <% Tag.where(post_id: post.id).each do |tag| %>
                          <span>#<%= tag.tag_name %></span>
                        <% end %>
                        <h3 class="post-subtitle"><%= post.content.slice(0,100) +"..." %></h3>
                    </a>
                    <p class="post-meta">
                      <%= t('views.posts.posted_by', user: User.find(post.user_id).name, date: l(post.created_at, format: :long)) %>
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
                <!-- Pager-->
            </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container my-4 px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <div class="post-preview">
        <h2 class="text-center"><%=t'Add_a_post' %></h2>
        <%= simple_form_for Post.new do |f| %>
          <%= f.input :title, label: (t'Post_title') %>
          <%= f.input :content, label: (t'Post_content') %>
          <div class="d-grid gap-2">
            <%= f.button :submit, (t'Post_create'), class: "btn btn-primary" %>
            <%= link_to "Cancel", :back, class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
      <hr class="my-5">
      <div class="post-upload">
        <%= form_tag(create_txt_posts_path, multipart: true) do %>
          <h2 class="text-center"><%= t'Upload_txt_files'%></h2>
          <div class="mb-3">
            <label for="txt-files" class="form-label"></label>
            <input type="file" class="form-control" id="txt-files" name="txt_files[]" multiple>
          </div>
          <div class="d-grid gap-2">
            <%= submit_tag (t'Post_create_txt'), class: "btn btn-primary" %>
            <%= link_to (t'Cancel'), :back, class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container my-4 px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      <div class="post-preview">
          <p>
            <h2 class="post-title text-center my-4"><%= @post.title %></h2>
            <h3 class="post-subtitle text-right"><%= @post.content%></h3>
            <% Tag.where(post_id: @post.id).each do |tag| %>
              <span>#<%= tag.tag_name %></span>
            <% end %>
          </p>
          <p class="post-meta">
            <%= t('views.posts.posted_by', user: User.find(@post.user_id).name, date: l(@post.created_at, format: :long)) %>
          </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      <!-- Pager-->
      <% if current_user == nil || current_user.id != @post.user_id%>
        <div class="d-flex mb-5 mt-2 div_post justify-content-center">
          <%= link_to (t'New_comment'), new_post_comment_path(@post), class:"btn btn-primary rounded text-uppercase"%>
        </div>
      <% else %>
        <div class="d-flex mb-5 mt-2 div_post justify-content-between">
          <%= link_to (t'Edit_post'), edit_post_path(@post), class:"btn btn-primary rounded text-uppercase"%>
          <%= link_to (t'New_comment'), new_post_comment_path(@post), class:"btn btn-primary rounded text-uppercase"%>
          <%= link_to (t'New_tag'), new_post_tag_path(@post), class:"btn btn-primary rounded text-uppercase"%>
          <%= link_to (t'Delete_this_post'), post_path(@post), data: {turbo_method: :delete, turbo_confirm: t('Are_you_sure?')}, class:"btn btn-primary rounded text-uppercase"%>
        </div>

      <% end %>
      <div>
        <% @post.comments.each do |comment| %>
          <div class="post-preview">
              <p>
                <% if  comment.user_id == 0 || comment.user_id == nil%>
                  <h4><%=t'Anonymous_user' %></h4>
                <% else %>
                  <h4><%= User.find(comment.user_id).name %></h4>
                <% end %>
                <h5 class="post-title text-right my-4"><%= comment.content %></h5>
              </p>
              <p class="post-meta">
                <%= t('views.posts.created_by', user: User.find(comment.user_id).name, date: l(comment.created_at, format: :long)) %>
              </p>
          </div>
          <!-- Divider-->
          <hr class="my-4" />
        <% end %>
      </div>
      <div class="d-flex justify-content-start mb-4">
        <a class="btn btn-primary text-uppercase" href="<%=posts_path%>">
          <%=t'Get_back_to_posts'%>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class:"d-flex rounded") do |f|%>
  <%= f.search_field :title_or_content_or_tags_tag_name_or_user_name_i_cont_any,
    placeholder: (t'Search'),
    class:"form-control rounded me-2"
  %>
  <%= f.submit (t'Search_button'), class:"btn btn-outline-success" %>
<% end %>

app/views/search/index.html.erb
<div>
  <div class="flex mb-4 mt-5 div_post ">
    <% if current_user != nil%>
      <%= link_to (t'New_post'), new_post_path, class:"popup_post row gx-4 fs-3 gx-lg-5 justify-content-center"%>
    <% end %>
  </div>
  <div>
    <%@posts.each do |post| %>
      <div class=" container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="<%= post_path(post)%>">
                        <h2 class="post-title"><%= post.title %></h2>
                        <% Tag.where(post_id: post.id).each do |tag| %>
                          <span>#<%= tag.tag_name %></span>
                        <% end %>
                        <h3 class="post-subtitle"><%= post.content.slice(0,100) +"..." %></h3>
                    </a>
                    <p class="post-meta">
                        Posted by <%= User.find(post.user_id).name %>
                        on <%= post.created_at.strftime("%B %d, %Y") %>
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
                <!-- Pager-->
            </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @posts %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <div class="container">
    <%= link_to posts_path, class: "navbar-brand" do %>
      <%= image_tag "blog.png", alt: "Blog" %>
    <% end %>

      <div>
        <%= render "search/form"%>
      </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active mx-2">
            <%= render "shared/notification" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar_square" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://img.icons8.com/?size=100&id=22396&format=png&color=000000", class: "avatar-square", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to (t"Edit_user_menu"), edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to (t'logout'), destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <li>
            <div class="mx-2 d-inline-flex">
              <div class="mx-1">
                <%= link_to url_for(locale: :en) do %>
                  <%= image_tag "https://img.icons8.com/?size=100&id=15532&format=png&color=000000", alt: "English", class: "flag-icon", height:"39px", width:"39px" %>
                <% end %>
              </div>
              <div class="mx-1">
                <%= link_to url_for(locale: :ptbr) do %>
                  <%= image_tag "https://img.icons8.com/?size=100&id=15509&format=png&color=000000", alt: "Português", class: "flag-icon",height:"40px", width:"40px" %>
                <% end %>
              </div>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to (t'login'), new_user_session_path, class: "btn btn-primary rounded text-uppercase" %>
          </li>
          <li>
            <div class="mx-2 d-inline-flex">
              <div class="mx-1">
                <%= link_to url_for(locale: :en) do %>
                  <%= image_tag "https://img.icons8.com/?size=100&id=15532&format=png&color=000000", alt: "English", class: "flag-icon", height:"39px", width:"39px" %>
                <% end %>
              </div>
              <div class="mx-1">
                <%= link_to url_for(locale: :ptbr) do %>
                  <%= image_tag "https://img.icons8.com/?size=100&id=15509&format=png&color=000000", alt: "Português", class: "flag-icon",height:"40px", width:"40px" %>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_notification.html.erb
<div class="dropdown">
  <button class="btn btn-secondary bg-dark-subtle rounded border-0 text-black dropdown-toggle" type="button" id="notificationDropdown" data-bs-toggle="dropdown" aria-expanded="false">
    <img src="<%= asset_path('notification.png') %>" width="20" height="25"> <%= Notification.where(user_id: current_user).count %>
  </button>
  <ul class="dropdown-menu" aria-labelledby="notificationDropdown">
    <% if Notification.where(user_id: current_user).count != 0 %>
      <% Notification.where(user_id: current_user).each do |notification| %>
        <li><%= link_to notification.post.title, post_path(notification.post_id) %></li>
      <% end %>
    <% else %>
      <li class="text-center"><%= t('there_is_no_notifications')%></li>
    <% end %>
  </ul>
</div>

app/views/tags/new.html.erb
<div class="container mb-4 mt-5 px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Tag form -->
      <div class="post-preview">
        <h2 class="text-center mb-5"><%= t'Add_a_tag'%></h2>
        <%= simple_form_for [@post, Tag.new] do |f| %>
          <%= f.input :tag_name, label: (t'Tags') %>
          <div class="d-grid gap-2">
            <%= f.button :submit, (t'Create_tag'), class: "btn btn-primary" %>
            <%= link_to (t'Cancel'), post_path(@post), class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>